=encoding utf8

=head1 LICENSE

=head2 Text

The text for these screenplays is original, but makes use of many characters
and concepts owned by various content owners.

As far as I am concerned, the blanket licence for the text is
the L<http://creativecommons.org/licenses/by-nc-sa/4.0/> (Unported), either
version 4.0 or at your option any later version.

=cut
