=encoding utf8

=head1 The Muppets Show - The New Incarnation

=head2 About

This repository contains the sources for some screenplays of a show
in a format similar to L<https://en.wikipedia.org/wiki/The_Muppet_Show>
with modern ( ~2014 ) cultural references.

The text for them is mostly original by Shlomi Fish
( L<http://www.shlomifish.org/> ).

=head2 Links

=over 4

=item * Homepage

L<http://www.shlomifish.org/humour/The-Muppet-Show--TNI/>

=back

=head2 Building

Go to C<Muppet-Show-TNI/screenplay/> and type C<make> .

=cut

