DOCS_BASE = Muppets-Show--Harry-Potter Muppets-Show--Summer-Glau-and-Chuck-Norris Muppets-Show--Jennifer-Lawrence

SELINA_UPLOAD_TEMP_DEST = temp-muppets-show-tni-LrE32Pnbw800

include $(SDIR)/screenplays_common.mak

